.pragma library

function getCountries() {
    return [
                {"code": "AF","name":"Afghanistan","calling":"+33"},
                {"code": "ZA","name":"Afrique du Sud","calling":"+33"},
                {"code": "AL","name":"Albanie","calling":"+33"},
                {"code": "DZ","name":"Algérie","calling":"+33"},
                {"code": "DE","name":"Allemagne","calling":"+33"},
                {"code": "AD","name":"Andorre","calling":"+33"},
                {"code": "AO","name":"Angola","calling":"+33"},
                {"code": "AI","name":"Anguilla","calling":"+33"},
                {"code": "AQ","name":"Antarctique","calling":"+33"},
                {"code": "AG","name":"Antigua-et-Barbuda","calling":"+33"},
                {"code": "SA","name":"Arabie saoudite","calling":"+33"},
                {"code": "AR","name":"Argentine","calling":"+33"},
                {"code": "AM","name":"Arménie","calling":"+33"},
                {"code": "AW","name":"Aruba","calling":"+33"},
                {"code": "AU","name":"Australie","calling":"+33"},
                {"code": "AT","name":"Autriche","calling":"+33"},
                {"code": "AZ","name":"Azerbaïdjan","calling":"+33"},
                {"code": "BS","name":"Bahamas","calling":"+33"},
                {"code": "BH","name":"Bahreïn","calling":"+33"},
                {"code": "BD","name":"Bangladesh","calling":"+33"},
                {"code": "BB","name":"Barbade","calling":"+33"},
                {"code": "BE","name":"Belgique","calling":"+33"},
                {"code": "BZ","name":"Belize","calling":"+33"},
                {"code": "BJ","name":"Bénin","calling":"+33"},
                {"code": "BM","name":"Bermudes","calling":"+33"},
                {"code": "BT","name":"Bhoutan","calling":"+33"},
                {"code": "BY","name":"Biélorussie","calling":"+33"},
                {"code": "BO","name":"Bolivie","calling":"+33"},
                {"code": "BA","name":"Bosnie-Herzégovine","calling":"+33"},
                {"code": "BW","name":"Botswana","calling":"+33"},
                {"code": "BR","name":"Brésil","calling":"+33"},
                {"code": "BN","name":"Brunéi Darussalam","calling":"+33"},
                {"code": "BG","name":"Bulgarie","calling":"+33"},
                {"code": "BF","name":"Burkina Faso","calling":"+33"},
                {"code": "BI","name":"Burundi","calling":"+33"},
                {"code": "KH","name":"Cambodge","calling":"+33"},
                {"code": "CM","name":"Cameroun","calling":"+33"},
                {"code": "CA","name":"Canada","calling":"+33"},
                {"code": "CV","name":"Cap-Vert","calling":"+33"},
                {"code": "CL","name":"Chili","calling":"+33"},
                {"code": "CN","name":"Chine","calling":"+33"},
                {"code": "CY","name":"Chypre","calling":"+33"},
                {"code": "CO","name":"Colombie","calling":"+33"},
                {"code": "KM","name":"Comores","calling":"+33"},
                {"code": "CG","name":"Congo-Brazzaville","calling":"+33"},
                {"code": "CD","name":"Congo-Kinshasa","calling":"+33"},
                {"code": "KP","name":"Corée du Nord","calling":"+33"},
                {"code": "KR","name":"Corée du Sud","calling":"+33"},
                {"code": "CR","name":"Costa Rica","calling":"+33"},
                {"code": "CI","name":"Côte d’Ivoire","calling":"+33"},
                {"code": "HR","name":"Croatie","calling":"+33"},
                {"code": "CU","name":"Cuba","calling":"+33"},
                {"code": "CW","name":"Curaçao","calling":"+33"},
                {"code": "DK","name":"Danemark","calling":"+33"},
                {"code": "DJ","name":"Djibouti","calling":"+33"},
                {"code": "DM","name":"Dominique","calling":"+33"},
                {"code": "EG","name":"Égypte","calling":"+33"},
                {"code": "AE","name":"Émirats arabes unis","calling":"+33"},
                {"code": "EC","name":"Équateur","calling":"+33"},
                {"code": "ER","name":"Érythrée","calling":"+33"},
                {"code": "ES","name":"Espagne","calling":"+33"},
                {"code": "EE","name":"Estonie","calling":"+33"},
                {"code": "SZ","name":"Eswatini","calling":"+33"},
                {"code": "VA","name":"État de la Cité du Vatican","calling":"+33"},
                {"code": "FM","name":"États fédérés de Micronésie","calling":"+33"},
                {"code": "US","name":"États-Unis","calling":"+33"},
                {"code": "ET","name":"Éthiopie","calling":"+33"},
                {"code": "FJ","name":"Fidji","calling":"+33"},
                {"code": "FI","name":"Finlande","calling":"+33"},
                {"code": "FR","name":"France","calling":"+33"},
                {"code": "GA","name":"Gabon","calling":"+33"},
                {"code": "GM","name":"Gambie","calling":"+33"},
                {"code": "GE","name":"Géorgie","calling":"+33"},
                {"code": "GS","name":"Géorgie du Sud et îles Sandwich du Sud","calling":"+33"},
                {"code": "GH","name":"Ghana","calling":"+33"},
                {"code": "GI","name":"Gibraltar","calling":"+33"},
                {"code": "GR","name":"Grèce","calling":"+33"},
                {"code": "GD","name":"Grenade","calling":"+33"},
                {"code": "GL","name":"Groenland","calling":"+33"},
                {"code": "GP","name":"Guadeloupe","calling":"+33"},
                {"code": "GU","name":"Guam","calling":"+33"},
                {"code": "GT","name":"Guatemala","calling":"+33"},
                {"code": "GG","name":"Guernesey","calling":"+33"},
                {"code": "GN","name":"Guinée","calling":"+33"},
                {"code": "GQ","name":"Guinée équatoriale","calling":"+33"},
                {"code": "GW","name":"Guinée-Bissau","calling":"+33"},
                {"code": "GY","name":"Guyana","calling":"+33"},
                {"code": "GF","name":"Guyane française","calling":"+33"},
                {"code": "HT","name":"Haïti","calling":"+33"},
                {"code": "HN","name":"Honduras","calling":"+33"},
                {"code": "HU","name":"Hongrie","calling":"+33"},
                {"code": "BV","name":"Île Bouvet","calling":"+33"},
                {"code": "CX","name":"Île Christmas","calling":"+33"},
                {"code": "IM","name":"Île de Man","calling":"+33"},
                {"code": "NF","name":"Île Norfolk","calling":"+33"},
                {"code": "AX","name":"Îles Åland","calling":"+33"},
                {"code": "KY","name":"Îles Caïmans","calling":"+33"},
                {"code": "CC","name":"Îles Cocos","calling":"+33"},
                {"code": "CK","name":"Îles Cook","calling":"+33"},
                {"code": "FO","name":"Îles Féroé","calling":"+33"},
                {"code": "HM","name":"Îles Heard et McDonald","calling":"+33"},
                {"code": "FK","name":"Îles Malouines","calling":"+33"},
                {"code": "MP","name":"Îles Mariannes du Nord","calling":"+33"},
                {"code": "MH","name":"Îles Marshall","calling":"+33"},
                {"code": "UM","name":"Îles mineures éloignées des États-Unis","calling":"+33"},
                {"code": "PN","name":"Îles Pitcairn","calling":"+33"},
                {"code": "SB","name":"Îles Salomon","calling":"+33"},
                {"code": "TC","name":"Îles Turques-et-Caïques","calling":"+33"},
                {"code": "VG","name":"Îles Vierges britanniques","calling":"+33"},
                {"code": "VI","name":"Îles Vierges des États-Unis","calling":"+33"},
                {"code": "IN","name":"Inde","calling":"+33"},
                {"code": "ID","name":"Indonésie","calling":"+33"},
                {"code": "IQ","name":"Irak","calling":"+33"},
                {"code": "IR","name":"Iran","calling":"+33"},
                {"code": "IE","name":"Irlande","calling":"+33"},
                {"code": "IS","name":"Islande","calling":"+33"},
                {"code": "IL","name":"Israël","calling":"+33"},
                {"code": "IT","name":"Italie","calling":"+33"},
                {"code": "JM","name":"Jamaïque","calling":"+33"},
                {"code": "JP","name":"Japon","calling":"+33"},
                {"code": "JE","name":"Jersey","calling":"+33"},
                {"code": "JO","name":"Jordanie","calling":"+33"},
                {"code": "KZ","name":"Kazakhstan","calling":"+33"},
                {"code": "KE","name":"Kenya","calling":"+33"},
                {"code": "KG","name":"Kirghizistan","calling":"+33"},
                {"code": "KI","name":"Kiribati","calling":"+33"},
                {"code": "KW","name":"Koweït","calling":"+33"},
                {"code": "RE","name":"La Réunion","calling":"+33"},
                {"code": "LA","name":"Laos","calling":"+33"},
                {"code": "LS","name":"Lesotho","calling":"+33"},
                {"code": "LV","name":"Lettonie","calling":"+33"},
                {"code": "LB","name":"Liban","calling":"+33"},
                {"code": "LR","name":"Libéria","calling":"+33"},
                {"code": "LY","name":"Libye","calling":"+33"},
                {"code": "LI","name":"Liechtenstein","calling":"+33"},
                {"code": "LT","name":"Lituanie","calling":"+33"},
                {"code": "LU","name":"Luxembourg","calling":"+33"},
                {"code": "MK","name":"Macédoine du Nord","calling":"+33"},
                {"code": "MG","name":"Madagascar","calling":"+261"},
                {"code": "MY","name":"Malaisie","calling":"+33"},
                {"code": "MW","name":"Malawi","calling":"+33"},
                {"code": "MV","name":"Maldives","calling":"+33"},
                {"code": "ML","name":"Mali","calling":"+33"},
                {"code": "MT","name":"Malte","calling":"+33"},
                {"code": "MA","name":"Maroc","calling":"+33"},
                {"code": "MQ","name":"Martinique","calling":"+33"},
                {"code": "MU","name":"Maurice","calling":"+33"},
                {"code": "MR","name":"Mauritanie","calling":"+33"},
                {"code": "YT","name":"Mayotte","calling":"+33"},
                {"code": "MX","name":"Mexique","calling":"+33"},
                {"code": "MD","name":"Moldavie","calling":"+33"},
                {"code": "MC","name":"Monaco","calling":"+33"},
                {"code": "MN","name":"Mongolie","calling":"+33"},
                {"code": "ME","name":"Monténégro","calling":"+33"},
                {"code": "MS","name":"Montserrat","calling":"+33"},
                {"code": "MZ","name":"Mozambique","calling":"+33"},
                {"code": "MM","name":"Myanmar (Birmanie)","calling":"+33"},
                {"code": "NA","name":"Namibie","calling":"+33"},
                {"code": "NR","name":"Nauru","calling":"+33"},
                {"code": "NP","name":"Népal","calling":"+33"},
                {"code": "NI","name":"Nicaragua","calling":"+33"},
                {"code": "NE","name":"Niger","calling":"+33"},
                {"code": "NG","name":"Nigéria","calling":"+33"},
                {"code": "NU","name":"Niue","calling":"+33"},
                {"code": "NO","name":"Norvège","calling":"+33"},
                {"code": "NC","name":"Nouvelle-Calédonie","calling":"+33"},
                {"code": "NZ","name":"Nouvelle-Zélande","calling":"+33"},
                {"code": "OM","name":"Oman","calling":"+33"},
                {"code": "UG","name":"Ouganda","calling":"+33"},
                {"code": "UZ","name":"Ouzbékistan","calling":"+33"},
                {"code": "PK","name":"Pakistan","calling":"+33"},
                {"code": "PW","name":"Palaos","calling":"+33"},
                {"code": "PA","name":"Panama","calling":"+33"},
                {"code": "PG","name":"Papouasie-Nouvelle-Guinée","calling":"+33"},
                {"code": "PY","name":"Paraguay","calling":"+33"},
                {"code": "NL","name":"Pays-Bas","calling":"+33"},
                {"code": "BQ","name":"Pays-Bas caribéens","calling":"+33"},
                {"code": "PE","name":"Pérou","calling":"+33"},
                {"code": "PH","name":"Philippines","calling":"+33"},
                {"code": "PL","name":"Pologne","calling":"+33"},
                {"code": "PF","name":"Polynésie française","calling":"+33"},
                {"code": "PR","name":"Porto Rico","calling":"+33"},
                {"code": "PT","name":"Portugal","calling":"+33"},
                {"code": "QA","name":"Qatar","calling":"+33"},
                {"code": "HK","name":"R.A.S. chinoise de Hong Kong","calling":"+33"},
                {"code": "MO","name":"R.A.S. chinoise de Macao","calling":"+33"},
                {"code": "CF","name":"République centrafricaine","calling":"+33"},
                {"code": "DO","name":"République dominicaine","calling":"+33"},
                {"code": "RO","name":"Roumanie","calling":"+33"},
                {"code": "GB","name":"Royaume-Uni","calling":"+33"},
                {"code": "RU","name":"Russie","calling":"+33"},
                {"code": "RW","name":"Rwanda","calling":"+33"},
                {"code": "EH","name":"Sahara occidental","calling":"+33"},
                {"code": "BL","name":"Saint-Barthélemy","calling":"+33"},
                {"code": "KN","name":"Saint-Christophe-et-Niévès","calling":"+33"},
                {"code": "SM","name":"Saint-Marin","calling":"+33"},
                {"code": "MF","name":"Saint-Martin","calling":"+33"},
                {"code": "SX","name":"Saint-Martin (partie néerlandaise)","calling":"+33"},
                {"code": "PM","name":"Saint-Pierre-et-Miquelon","calling":"+33"},
                {"code": "VC","name":"Saint-Vincent-et-les-Grenadines","calling":"+33"},
                {"code": "SH","name":"Sainte-Hélène","calling":"+33"},
                {"code": "LC","name":"Sainte-Lucie","calling":"+33"},
                {"code": "SV","name":"Salvador","calling":"+33"},
                {"code": "WS","name":"Samoa","calling":"+33"},
                {"code": "AS","name":"Samoa américaines","calling":"+33"},
                {"code": "ST","name":"Sao Tomé-et-Principe","calling":"+33"},
                {"code": "SN","name":"Sénégal","calling":"+33"},
                {"code": "RS","name":"Serbie","calling":"+33"},
                {"code": "SC","name":"Seychelles","calling":"+33"},
                {"code": "SL","name":"Sierra Leone","calling":"+33"},
                {"code": "SG","name":"Singapour","calling":"+33"},
                {"code": "SK","name":"Slovaquie","calling":"+33"},
                {"code": "SI","name":"Slovénie","calling":"+33"},
                {"code": "SO","name":"Somalie","calling":"+33"},
                {"code": "SD","name":"Soudan","calling":"+33"},
                {"code": "SS","name":"Soudan du Sud","calling":"+33"},
                {"code": "LK","name":"Sri Lanka","calling":"+33"},
                {"code": "SE","name":"Suède","calling":"+33"},
                {"code": "CH","name":"Suisse","calling":"+33"},
                {"code": "SR","name":"Suricode","calling":"+33"},
                {"code": "SJ","name":"Svalbard et Jan Mayen","calling":"+33"},
                {"code": "SY","name":"Syrie","calling":"+33"},
                {"code": "TJ","name":"Tadjikistan","calling":"+33"},
                {"code": "TW","name":"Taïwan","calling":"+33"},
                {"code": "TZ","name":"Tanzanie","calling":"+33"},
                {"code": "TD","name":"Tchad","calling":"+33"},
                {"code": "CZ","name":"Tchéquie","calling":"+33"},
                {"code": "TF","name":"Terres australes françaises","calling":"+33"},
                {"code": "IO","name":"Territoire britannique de l’océan Indien","calling":"+33"},
                {"code": "PS","name":"Territoires palestiniens","calling":"+33"},
                {"code": "TH","name":"Thaïlande","calling":"+33"},
                {"code": "TL","name":"Timor oriental","calling":"+33"},
                {"code": "TG","name":"Togo","calling":"+33"},
                {"code": "TK","name":"Tokelau","calling":"+33"},
                {"code": "TO","name":"Tonga","calling":"+33"},
                {"code": "TT","name":"Trinité-et-Tobago","calling":"+33"},
                {"code": "TN","name":"Tunisie","calling":"+33"},
                {"code": "TM","name":"Turkménistan","calling":"+33"},
                {"code": "TR","name":"Turquie","calling":"+33"},
                {"code": "TV","name":"Tuvalu","calling":"+33"},
                {"code": "UA","name":"Ukraine","calling":"+33"},
                {"code": "UY","name":"Uruguay","calling":"+33"},
                {"code": "VU","name":"Vanuatu","calling":"+33"},
                {"code": "VE","name":"Venezuela","calling":"+33"},
                {"code": "VN","name":"Vietnam","calling":"+33"},
                {"code": "WF","name":"Wallis-et-Futuna","calling":"+33"},
                {"code": "YE","name":"Yémen","calling":"+33"},
                {"code": "ZM","name":"Zambie","calling":"+33"},
                {"code": "ZW","name":"Zimbabwe","calling":"+33"},
               ]
}
